import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth";

export async function GET() {
  await requireRole(["ADMIN"]);
  const [
    settings,
    branches,
    users,
    categories,
    units,
    products,
    productStocks,
    customers,
    suppliers,
    customerLedger,
    supplierLedger,
    sales,
    saleItems,
    saleReturns,
    saleReturnItems,
    purchases,
    purchaseItems,
    purchaseReturns,
    purchaseReturnItems,
    stockMoves,
    stockTransfers,
    stockAdjustments,
    expenseCategories,
    expenses,
    accounts,
    accountTxns,
    employees,
    salaryPayments,
  ] = await Promise.all([
    prisma.setting.findMany(),
    prisma.branch.findMany(),
    prisma.user.findMany({
      select: {
        id: true,
        name: true,
        email: true,
        role: true,
        branchId: true,
        active: true,
        createdAt: true,
      },
    }),
    prisma.category.findMany(),
    prisma.unit.findMany(),
    prisma.product.findMany(),
    prisma.productStock.findMany(),
    prisma.customer.findMany(),
    prisma.supplier.findMany(),
    prisma.customerLedger.findMany(),
    prisma.supplierLedger.findMany(),
    prisma.sale.findMany(),
    prisma.saleItem.findMany(),
    prisma.saleReturn.findMany(),
    prisma.saleReturnItem.findMany(),
    prisma.purchase.findMany(),
    prisma.purchaseItem.findMany(),
    prisma.purchaseReturn.findMany(),
    prisma.purchaseReturnItem.findMany(),
    prisma.stockMove.findMany(),
    prisma.stockTransfer.findMany(),
    prisma.stockAdjustment.findMany(),
    prisma.expenseCategory.findMany(),
    prisma.expense.findMany(),
    prisma.account.findMany(),
    prisma.accountTxn.findMany(),
    prisma.employee.findMany(),
    prisma.salaryPayment.findMany(),
  ]);
  const payload = {
    version: 1,
    exportedAt: new Date().toISOString(),
    settings,
    branches,
    users,
    categories,
    units,
    products,
    productStocks,
    customers,
    suppliers,
    customerLedger,
    supplierLedger,
    sales,
    saleItems,
    saleReturns,
    saleReturnItems,
    purchases,
    purchaseItems,
    purchaseReturns,
    purchaseReturnItems,
    stockMoves,
    stockTransfers,
    stockAdjustments,
    expenseCategories,
    expenses,
    accounts,
    accountTxns,
    employees,
    salaryPayments,
  };
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  return new NextResponse(JSON.stringify(payload, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Content-Disposition": `attachment; filename="erp-backup-${ts}.json"`,
    },
  });
}
